vulnerabilities:
  - id: CVE-2026-25128
    statement: downstream dependency for fast-xml-parser - waiting for redocly update
    expired_at: 2026-03-01
  - id: CVE-2026-25547
    statement: downstream dependency for glob - waiting for redocly update
    expired_at: 2026-03-01
