vulnerabilities:
  - id: CVE-2026-25128
    statement: downstream dependency for fast-xml-parser - waiting for redocly update
    expired_at: 2026-04-01
  - id: CVE-2026-26278
    statement: downstream dependency for fast-xml-parser - waiting for aws-cdk update
    expired_at: 2026-04-01
  - id: CVE-2026-25547
    statement: downstream dependency for @isaacs/brace-expansion - waiting for redocly update
    expired_at: 2026-04-01
  - id: CVE-2026-25639
    statement:  axios vulnerability accepted as risk - dependency of axios-retry
    expired_at: 2026-04-01
