/* eslint-disable max-len */
// JSON (OK) Responses
import {SpineJsonResponse} from "../../src/parseSpineResponse"
import singleAcuteRaw from "./singleAcute.json"
import singleErdRaw from "./singleErd.json"
import singleRepeatRaw from "./singleRepeat.json"
import multipleAcuteRaw from "./multipleAcute.json"
import multipleErdRaw from "./multipleErd.json"
import multipleRepeatRaw from "./multipleRepeat.json"
import multipleMixedRaw from "./multipleMixed.json"
const singleAcute = singleAcuteRaw as SpineJsonResponse
const singleErd = singleErdRaw as SpineJsonResponse
const singleRepeat = singleRepeatRaw as SpineJsonResponse
const multipleAcute = multipleAcuteRaw as SpineJsonResponse
const multipleErd = multipleErdRaw as SpineJsonResponse
const multipleRepeat = multipleRepeatRaw as SpineJsonResponse
const multipleMixed = multipleMixedRaw as SpineJsonResponse
export {singleAcute, singleErd, singleRepeat, multipleAcute, multipleErd, multipleRepeat, multipleMixed}

// XML (Error) Responses
export const error = "<?xml version='1.0' encoding='UTF-8'?>\n<SOAP:Envelope xmlns:crs=\"http://national.carerecords.nhs.uk/schema/crs/\" xmlns:SOAP=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:wsa=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns=\"urn:hl7-org:v3\" xmlns:hl7=\"urn:hl7-org:v3\"><SOAP:Header><wsa:MessageID>uuid:example-guid</wsa:MessageID><wsa:Action>urn:nhs:names:services:pdsquery/MCCI_IN010000UK13</wsa:Action><wsa:To/><wsa:From><wsa:Address>https://pdsquery.national.ncrs.nhs.uk/syncservice</wsa:Address></wsa:From><communicationFunctionRcv typeCode=\"RCV\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionRcv><communicationFunctionSnd typeCode=\"SND\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionSnd><wsa:RelatesTo>uuid:example-request-GUID</wsa:RelatesTo></SOAP:Header><SOAP:Body><prescriptionSearchResponse><MCCI_IN010000UK13><id root=\"example-guid\"/><creationTime value=\"19700101000000\"/><versionCode code=\"V3NPfIT3.0\"/><interactionId root=\"2.16.840.1.113883.2.1.3.2.4.12\" extension=\"MCCI_IN010000UK13\"/><processingCode code=\"P\"/><processingModeCode code=\"T\"/><acceptAckCode code=\"NE\"/><acknowledgement typeCode=\"AR\"><acknowledgementDetail typeCode=\"ER\"><code codeSystem=\"PRESCRIPTION_SEARCH_ERROR\" code=\"0005\" displayName=\"Invalid prescription checksum\"/></acknowledgementDetail><messageRef><id root=\"example-request-GUID\"/></messageRef></acknowledgement><communicationFunctionRcv typeCode=\"RCV\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionRcv><communicationFunctionSnd typeCode=\"SND\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionSnd><ControlActEvent classCode=\"CACT\" moodCode=\"EVN\"><author1 typeCode=\"AUT\"><AgentSystemSDS classCode=\"AGNT\"><agentSystemSDS classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></agentSystemSDS></AgentSystemSDS></author1></ControlActEvent></MCCI_IN010000UK13></prescriptionSearchResponse></SOAP:Body></SOAP:Envelope>"
export const notFound = "<?xml version='1.0' encoding='UTF-8'?>\n<SOAP:Envelope xmlns:crs=\"http://national.carerecords.nhs.uk/schema/crs/\" xmlns:SOAP=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:wsa=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns=\"urn:hl7-org:v3\" xmlns:hl7=\"urn:hl7-org:v3\"><SOAP:Header><wsa:MessageID>uuid:example-guid</wsa:MessageID><wsa:Action>urn:nhs:names:services:pdsquery/MCCI_IN010000UK13</wsa:Action><wsa:To/><wsa:From><wsa:Address>https://pdsquery.national.ncrs.nhs.uk/syncservice</wsa:Address></wsa:From><communicationFunctionRcv typeCode=\"RCV\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionRcv><communicationFunctionSnd typeCode=\"SND\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionSnd><wsa:RelatesTo>uuid:example-request-GUID</wsa:RelatesTo></SOAP:Header><SOAP:Body><prescriptionSearchResponse><MCCI_IN010000UK13><id root=\"example-guid\"/><creationTime value=\"19700101000000\"/><versionCode code=\"V3NPfIT3.0\"/><interactionId root=\"2.16.840.1.113883.2.1.3.2.4.12\" extension=\"MCCI_IN010000UK13\"/><processingCode code=\"P\"/><processingModeCode code=\"T\"/><acceptAckCode code=\"NE\"/><acknowledgement typeCode=\"AR\"><acknowledgementDetail typeCode=\"ER\"><code codeSystem=\"PRESCRIPTION_SEARCH_ERROR\" code=\"0001\" displayName=\"Prescription not found\"/></acknowledgementDetail><messageRef><id root=\"example-request-GUID\"/></messageRef></acknowledgement><communicationFunctionRcv typeCode=\"RCV\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionRcv><communicationFunctionSnd typeCode=\"SND\"><device classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></device></communicationFunctionSnd><ControlActEvent classCode=\"CACT\" moodCode=\"EVN\"><author1 typeCode=\"AUT\"><AgentSystemSDS classCode=\"AGNT\"><agentSystemSDS classCode=\"DEV\" determinerCode=\"INSTANCE\"><id root=\"1.2.826.0.1285.0.2.0.107\" extension=\"200000002066\"/></agentSystemSDS></AgentSystemSDS></author1></ControlActEvent></MCCI_IN010000UK13></prescriptionSearchResponse></SOAP:Body></SOAP:Envelope>"
