AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  CPT resources

Parameters:
  EnableMutualTLS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  TruststoreVersion:
    Type: String
    Default: none

  TargetSpineServer:
    Type: String
    Default: none

  LogLevel:
    Type: String
    Default: "INFO"

  LogRetentionInDays:
    Type: Number
    Default: 30
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1096,
        1827,
        2192,
        2557,
        2922,
        3288,
        3653,
      ]

  EnableSplunk:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

Resources:
  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreVersion: !Ref TruststoreVersion
        TargetSpineServer: !Ref TargetSpineServer
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId
