/* eslint-disable max-len */
import {readFileSync} from "fs"
import path from "path"

const readXmlToString = (filename: string) => {
  return readFileSync(path.resolve("tests/examples", filename)).toString()
}

export const acuteCreated = readXmlToString("acuteCreated.xml")
export const acuteNonNominatedCreated = readXmlToString("acuteNonNominatedCreated.xml")
export const acuteReleased = readXmlToString("acuteReleased.xml")
export const acuteDispensed = readXmlToString("acuteDispensed.xml")
export const acuteDispensedWithASingleItem = readXmlToString("acuteDispensedWithSingleItem.xml")
export const acuteDispensedWithMultipleComponents = readXmlToString("acuteDispensedWithMultipleComponents.xml")
export const acuteCancelled = readXmlToString("acuteCancelled.xml")
export const acuteWithCancelledItem = readXmlToString("acuteWithCancelledItem.xml")
export const acutePartiallyDispensed = readXmlToString("acutePartiallyDispensed.xml")
export const acuteWithItemPartiallyDispensed = readXmlToString("acuteWithItemPartiallyDispensed.xml")
export const acuteCumulativeMultipleDispenseNotifications = readXmlToString("acuteCumulativeMultipleDispenseNotifications.xml")
export const acuteAdditiveMultipleDispenseNotifications = readXmlToString("acuteAdditiveMultipleDispenseNotifications.xml")
export const altAcuteAdditiveMultipleDispenseNotifications = readXmlToString("altAcuteAdditiveMultipleDispenseNotifications.xml")
export const acutePendingCancellation = readXmlToString("acutePendingCancellation.xml")
export const acuteWithItemPendingCancellation = readXmlToString("acuteWithItemPendingCancellation.xml")
export const acuteHl7PendingCancellation = readXmlToString("acuteHl7PendingCancellation.xml")
export const acuteHl7Cancelled =readXmlToString("acuteHl7Cancelled.xml")
export const acuteWithoutOptionalPatientDetails = readXmlToString("acuteWithoutOptionalPatientDetails.xml")
export const acuteWithoutOptionalDaysSupply = readXmlToString("acuteWithoutOptionalDaysSupply.xml")
export const acuteWithEmptyDosageInstructions = readXmlToString("acuteWithEmptyDosageInstructions.xml")
export const acuteWithoutOptionalDosageInstructions = readXmlToString("acuteWithoutOptionalDosageInstructions.xml")
export const acuteWithPartialDispenseNotification = readXmlToString("acuteWithPartialDispenseNotification.xml")
export const acuteWithWithdrawnDispenseNotification = readXmlToString("acuteWithWithdrawnDispenseNotification.xml")
export const acuteWithWithdrawnAmendment = readXmlToString("acuteWithWithdrawnAmendment.xml")
export const acuteWithdrawn = readXmlToString("acuteWithdrawn.xml")
export const acuteDispensedWithMismatchedIds = readXmlToString("acuteDispensedWithMismatchedIds.xml")
export const acuteMultipleDispenseNotificationsWithMismatchedIds = readXmlToString("acuteMultipleDispenseNotificationsWithMismatchedIds.xml")
export const erdCreated = readXmlToString("erdCreated.xml")
export const erdDispensedWith0Quantity = readXmlToString("erdDispensedWith0Quantity.xml")
export const notFound = readXmlToString("notFound.xml")
export const unknownError = readXmlToString("unknownError.xml")
export const malformedError = readXmlToString("malformedError.xml")
